CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  nickname VARCHAR(50) DEFAULT '',
  email VARCHAR(100) DEFAULT '',
  phone VARCHAR(20) DEFAULT '',
  avatar VARCHAR(200) DEFAULT '',
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  role_key VARCHAR(50) NOT NULL UNIQUE,
  role_name VARCHAR(50) NOT NULL,
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_menu (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  parent_id BIGINT DEFAULT 0,
  name VARCHAR(50) NOT NULL,
  path VARCHAR(200) DEFAULT '',
  component VARCHAR(200) DEFAULT '',
  icon VARCHAR(50) DEFAULT '',
  perms VARCHAR(100) DEFAULT '' COMMENT '权限标识',
  menu_type CHAR(1) NOT NULL COMMENT 'M=目录 C=菜单 F=按钮',
  sort INT DEFAULT 0,
  visible INT DEFAULT 0 COMMENT '0=显示 1=隐藏',
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_role_menu (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, menu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 部门表
CREATE TABLE IF NOT EXISTS sys_dept (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  parent_id BIGINT DEFAULT 0,
  dept_name VARCHAR(50) NOT NULL,
  order_num INT DEFAULT 0,
  leader VARCHAR(50) DEFAULT '',
  phone VARCHAR(20) DEFAULT '',
  email VARCHAR(100) DEFAULT '',
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 岗位表
CREATE TABLE IF NOT EXISTS sys_post (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_code VARCHAR(50) NOT NULL UNIQUE,
  post_name VARCHAR(50) NOT NULL,
  post_sort INT DEFAULT 0,
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 字典类型表
CREATE TABLE IF NOT EXISTS sys_dict_type (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dict_name VARCHAR(100) NOT NULL,
  dict_type VARCHAR(100) NOT NULL UNIQUE,
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 字典数据表
CREATE TABLE IF NOT EXISTS sys_dict_data (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dict_type_id BIGINT NOT NULL,
  dict_label VARCHAR(100) NOT NULL,
  dict_value VARCHAR(100) NOT NULL,
  dict_sort INT DEFAULT 0,
  status INT DEFAULT 0 COMMENT '0=正常 1=停用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 参数配置表
CREATE TABLE IF NOT EXISTS sys_config (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  config_name VARCHAR(100) NOT NULL,
  config_key VARCHAR(100) NOT NULL UNIQUE,
  config_value VARCHAR(500) NOT NULL,
  config_type INT DEFAULT 0 COMMENT '0=内置 1=自定义',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 通知公告表
CREATE TABLE IF NOT EXISTS sys_notice (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  notice_title VARCHAR(100) NOT NULL,
  notice_type INT DEFAULT 1 COMMENT '1=通知 2=公告',
  notice_content TEXT,
  status INT DEFAULT 0 COMMENT '0=正常 1=关闭',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 操作日志表
CREATE TABLE IF NOT EXISTS sys_oper_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) DEFAULT '',
  business_type INT DEFAULT 0,
  method VARCHAR(200) DEFAULT '',
  request_method VARCHAR(10) DEFAULT '',
  oper_name VARCHAR(50) DEFAULT '',
  oper_url VARCHAR(200) DEFAULT '',
  oper_ip VARCHAR(50) DEFAULT '',
  oper_param TEXT,
  json_result TEXT,
  status INT DEFAULT 0 COMMENT '0=正常 1=异常',
  error_msg TEXT,
  oper_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 登录日志表
CREATE TABLE IF NOT EXISTS sys_login_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT '',
  status INT DEFAULT 0 COMMENT '0=成功 1=失败',
  ip_addr VARCHAR(50) DEFAULT '',
  msg VARCHAR(200) DEFAULT '',
  login_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AI对话表
CREATE TABLE IF NOT EXISTS ai_conversation (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL DEFAULT '新对话',
  user_id BIGINT NOT NULL,
  model_id VARCHAR(50) DEFAULT '',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_conv_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AI消息表
CREATE TABLE IF NOT EXISTS ai_message (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL COMMENT 'user/assistant/system',
  content TEXT NOT NULL,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_msg_conv (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AI模型表
CREATE TABLE IF NOT EXISTS ai_model (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  model_key VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'API模型标识，如deepseek-chat',
  name VARCHAR(100) NOT NULL,
  provider VARCHAR(50) NOT NULL DEFAULT '' COMMENT '提供商标识: deepseek/openai/qwen/zhipu/moonshot',
  capabilities VARCHAR(200) DEFAULT '' COMMENT '逗号分隔: chat,code,reasoning',
  api_base_url VARCHAR(300) DEFAULT '' COMMENT 'API基础URL，为空则使用默认配置',
  api_key VARCHAR(200) DEFAULT '' COMMENT '模型专属API密钥，为空则使用全局配置',
  sort INT DEFAULT 0 COMMENT '排序号',
  status INT DEFAULT 0 COMMENT '0=启用 1=禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AI知识库表
CREATE TABLE IF NOT EXISTS ai_knowledge_base (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) DEFAULT '',
  status INT DEFAULT 0 COMMENT '0=启用 1=禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AI用户配置表
CREATE TABLE IF NOT EXISTS ai_config (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  temperature DOUBLE DEFAULT 0.7,
  max_tokens INT DEFAULT 2048,
  system_prompt VARCHAR(2000) DEFAULT '你是一个有帮助的AI助手，请用简洁清晰的中文回答问题。',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 定时任务表
CREATE TABLE IF NOT EXISTS sys_job (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  job_name VARCHAR(100) NOT NULL,
  job_group VARCHAR(50) DEFAULT '',
  invoke_target VARCHAR(200) DEFAULT '',
  cron_expression VARCHAR(200) DEFAULT '',
  status INT DEFAULT 0 COMMENT '0=正常 1=暂停',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 站点配置表
CREATE TABLE IF NOT EXISTS sys_site_config (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  config_key VARCHAR(100) NOT NULL UNIQUE,
  config_value VARCHAR(500) NOT NULL DEFAULT '',
  config_name VARCHAR(100) NOT NULL COMMENT '配置名称',
  remark VARCHAR(200) DEFAULT '' COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 助手分类表
CREATE TABLE IF NOT EXISTS ai_assistant_category (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  sort INT DEFAULT 0,
  status INT DEFAULT 0 COMMENT '0=启用 1=禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 系统错误码表（中英文双语，Redis缓存）
CREATE TABLE IF NOT EXISTS sys_error_code (
  code INT PRIMARY KEY COMMENT '错误码',
  zh_msg VARCHAR(200) NOT NULL DEFAULT '' COMMENT '中文消息',
  en_msg VARCHAR(200) NOT NULL DEFAULT '' COMMENT '英文消息',
  module VARCHAR(50) NOT NULL DEFAULT '' COMMENT '所属模块',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AI文档表（用户上传的文件解析存储）
CREATE TABLE IF NOT EXISTS ai_document (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '原始文件名',
  file_type VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'MIME类型',
  file_size BIGINT DEFAULT 0 COMMENT '文件大小(字节)',
  content MEDIUMTEXT COMMENT 'Tika解析后的文本内容',
  user_id BIGINT NOT NULL COMMENT '上传用户ID',
  conversation_id BIGINT DEFAULT NULL COMMENT '关联对话ID（可选）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_doc_user (user_id),
  INDEX idx_doc_conv (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 对话收藏表
CREATE TABLE IF NOT EXISTS ai_favorite (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  conversation_id BIGINT NOT NULL,
  group_id BIGINT DEFAULT NULL COMMENT '所属分组ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX uniq_user_conv (user_id, conversation_id),
  INDEX idx_fav_user (user_id),
  INDEX idx_fav_group (group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 迁移：为已有ai_favorite表添加group_id列（如不存在）
-- ALTER TABLE ai_favorite ADD COLUMN IF NOT EXISTS group_id BIGINT DEFAULT NULL COMMENT '所属分组ID' AFTER conversation_id;

-- 收藏分组表
CREATE TABLE IF NOT EXISTS ai_favorite_group (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  sort INT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_fg_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 助手模板表
CREATE TABLE IF NOT EXISTS ai_assistant (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) DEFAULT '',
  icon VARCHAR(50) DEFAULT '' COMMENT 'Element Plus图标名',
  prompt TEXT NOT NULL COMMENT 'System Prompt预设',
  sort INT DEFAULT 0,
  status INT DEFAULT 0 COMMENT '0=启用 1=禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 消息评分表
CREATE TABLE IF NOT EXISTS ai_message_rating (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  message_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  conversation_id BIGINT NOT NULL,
  rating INT NOT NULL COMMENT '1=赞 0=踩',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX uniq_msg_user (message_id, user_id),
  INDEX idx_rating_conv (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 对话分享表
CREATE TABLE IF NOT EXISTS ai_share (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  share_token VARCHAR(64) NOT NULL UNIQUE COMMENT '分享唯一标识',
  is_active INT DEFAULT 1 COMMENT '1=有效 0=已撤销',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_share_token (share_token),
  INDEX idx_share_conv (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
